class CounsellingApplicationForm {
  constructor(id, firstname, lastname, address, phonenumber, email, bdate, gender) {
    this.id = id; // represents the id generated by the firestore
    this.firstname = firstname;
    this.lastname = lastname;
    this.address = address;
    this.phonenumber = phonenumber;
    this.email = email;
    this.bdate = bdate;
    this.gender = gender;
  }
}

module.exports = CounsellingApplicationForm;
