class CounsellingApplicationForm {
  constructor(id, firstName, lastName, address, telephone, email, bdate, gender, status) {
    this.id = id; // represents the id generated by the firestore
    this.firstName = firstName;
    this.lastName = lastName;
    this.address = address;
    this.telephone = telephone;
    this.email = email;
    this.bdate = bdate;
    this.gender = gender;
    this.status = status;
  }
}

module.exports = CounsellingApplicationForm;
